### ISSUE TITLE
Nation Designer points

### ISSUE THREAD

**Issue by lucky13pjn** [lucky13pjn/OmicronsCheats#6]
Add more points in nation designer.

**Comment by lucky13pjn** [comment]
If this requires modification to the defines.lua, then it will not be implemented for maximum compatibility.

**Comment by Martin-21** [comment]
I think that's more compatible than edit defines.lua directly: http://1drv.ms/1M4teCA

**Comment by lucky13pjn** [comment]
Hmm, interesting. I didn't even know that they added (or always had) a way to have granular overrides to the defines.lua. Thank you for pointing that out :+1:.

**Comment by lucky13pjn** [comment]
Added common/defines/OC_defines.lua

Overrode Nation Designer available points to 10000.
